### PR TITLE
words

### PR DESCRIPTION
**Pull request by royaleconqueso**

### CODE REVIEW

**Comment by royaleconqueso** [comment]
Why should some stranger in the world fork it? So they can make a pull request. You can't send a pull request unless you're a contributor, or unless you fork the project.

**Comment by llamakc** [comment]
To-do: remove instruction to fork as that is implied with any PR as explained (by contributor)

**Comment by royaleconqueso** [comment]
Fair enough. Lemme figure out how to edit a PR after it's already submitted

**Comment by royaleconqueso** [comment]
Wait, you already merged it. Now it's yours so you have to edit it.

To-do: Please fix the instructions because anyone doing a PR already knows they obviously have to fork it first.

**Pull request merged**
